# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#
# version format
version: 1.0.3.{build}

# branches to build
branches:
  # whitelist
  only:
    - master
    - develop

  # blacklist
  except:
    - gh-pages

# environment variables
environment:
  VERSION_BRANCH: $(APPVEYOR_BUILD_VERSION)-$(APPVEYOR_REPO_BRANCH)
  SOLUTION_NAME: Windows Server Advanced Power Management Plugins
  PROJECT_NAME: OpenNetworkConnections
  ARTIFACT_NAME: WSAPM-OpenNetworkConnections-v$(APPVEYOR_BUILD_VERSION)
  GITHUB_TAG_NAME_BRANCH_MASTER: version/$(APPVEYOR_BUILD_VERSION)
  GITHUB_RELEASE_NAME_BRANCH_MASTER: v$(APPVEYOR_BUILD_VERSION)-master
  GITHUB_AUTH_TOKEN:
    secure: Lt14H6VdlEhGTEo0X7E0MJXdOiAkaGpGA08+khTJeNHXgc8qIBoMqHOotJHJlLiG

# Do not build on tags (GitHub only)
skip_tags: true

# Skipping commits with particular message or from user
#skip_commits:
#  message: /appveyor:(.*)/

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os:
  - Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:

# clone directory
#clone_folder: c:\projects\myproject

# build cache to preserve files/folders between builds
cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

# scripts that run after cloning repository
# use - ps for powershell, - cmd for commandline
install:
  - cmd: nuget restore
#  - cmd: cmake --version
#  - cmd: msbuild /version

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"


#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform:
  - Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration:
  - Debug
  - Release

build:
  parallel: true                   # enable MSBuild parallel builds
  project: $(SOLUTION_NAME).sln     # path to Visual Studio solution or project
  # MSBuild verbosity level
  verbosity: minimal                # quiet|minimal|normal|detailed

# scripts to run before build
before_build:

# scripts to run after build
after_build:

# to run your custom scripts instead of automatic MSBuild
#build_script:

# to disable automatic builds
#build: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: $(PROJECT_NAME)\bin\$(CONFIGURATION)\
    name: $(ARTIFACT_NAME)-$(CONFIGURATION)

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# providers: Local, FTP, GitHub, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
deploy:
  # Master branch, deploy to github
  - provider: GitHub
    auth_token: $(GITHUB_AUTH_TOKEN)
    tag: $(GITHUB_TAG_NAME_BRANCH_MASTER)
    release: $(GITHUB_RELEASE_NAME_BRANCH_MASTER)
    # description needs to be declared, but can be empty, so that github not reject the deploy
    description: ""
    artifact: $(ARTIFACT_NAME)-$(CONFIGURATION)
    draft: false
    prerelease: true
    on:
      branch: master                 # release from master branch only
      #APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED: /(.*)appveyor:deploy/
      #appveyor_repo_tag: false       # deploy on tag push only; default: true


# to disable deployment
#deploy: off

# scripts to run before deployment
before_deploy:
#  - ps: Get-ChildItem Env:*
#  - ps: ls "${Env:PROJECT_NAME}\bin"
#  - ps: ls "${Env:PROJECT_NAME}\bin\${Env:configuration}"

# scripts to run after deployment
after_deploy:

# to run your custom scripts instead of provider deployments
deploy_script:

#---------------------------------#
#        global handlers          #
#---------------------------------#

# on successful build
# on_success:
#   - do something

# on build failure
# on_failure:
#   - do something

# after build failure or success
# on_finish:
#   - do something